const fs = require('fs');
let content = fs.readFileSync('src/screens/Financials.tsx', 'utf8');

const regexPayload = /const newInvoicePayload = {[\s\S]*?sentAt: serverTimestamp\(\),\s*};/;
const updatedPayload = `const newInvoicePayload = {
                ...inv,
                id: undefined,
                isRecurring: false, // The instance is not the recurring definition
                recurringSchedule: "none",
                parentInvoiceId: inv.id,
                invoiceNumber: \`\${inv.invoiceNumber}-\${Math.floor(Math.random() * 10000)}\`,
                autoGenerated: true,
                sentAt: serverTimestamp(),
              };`;
content = content.replace(regexPayload, updatedPayload);

const regexInvoiceNumber = /<span className="font-medium text-white text-sm">[\s\S]*?\{inv\.invoiceNumber\}[\s\S]*?<\/span>/;
const updatedInvoiceNumber = `<span className="font-medium text-white text-sm flex items-center gap-2">
                              {inv.invoiceNumber}
                              {inv.autoGenerated && (
                                <span className="text-[9px] bg-indigo-500/20 text-indigo-300 px-1.5 py-0.5 rounded border border-indigo-500/30 uppercase tracking-widest font-bold">Auto-Gen</span>
                              )}
                              {inv.isRecurring && inv.recurringSchedule !== 'none' && (
                                <span className="text-[9px] bg-[#ff0000]/20 text-[#ff0000] px-1.5 py-0.5 rounded border border-[#ff0000]/30 uppercase tracking-widest font-bold">{inv.recurringSchedule}</span>
                              )}
                            </span>`;
content = content.replace(regexInvoiceNumber, updatedInvoiceNumber);

fs.writeFileSync('src/screens/Financials.tsx', content);
console.log('updated invoice payload and ui');
